FormSchemas/jsonschema.json, FormSchemas/uischema.json
I had `[` brackets instead of parentheses '{' so RJSF hid the roles options
=> fix: roles within items_assets not displayed do to brackets

FormSchemas/jsonschema.json, FormSchemas/uischema.json
The dataset configs typically do not include the `dashboard:` prefix.  For example: 
```
{ ...
"is_periodic": true,
"time_density": "day",
```
To ensure that the manual json can parse these values, this PR removes the `dashboard: ` prefix from the form.
=> Remove dashboard prefix for time density and is_periodic

__mocks__/handlers.ts, __tests__/playwright/COGControlsForm.test.tsx, components/COGControlsForm.tsx
With so many colormap options, it seems easier to allow a user to search as well as scroll through the dropdown options.
=> add search option to cog controls select components

middleware.ts
in testing locally with `NEXT_PUBLIC_DISABLE_AUTH=true`, @slesaad discovered that the protected routes still returned a `401` if not authenticated.  This short circuits the middleware auth check if that env variable is true.
=> allow unauthenticated api calls if NEXT_PUBLIC_DISABLE_AUTH=true

README.md
This adds to the readme sections for both Cognito and Github app configuration to hopefully make things easier if we need to do the setup again in the future.
=> document cognito and github confiuration

__tests__/playwright/CreateIngestPage.test.tsx, components/JSONEditor.tsx
This is just a small tweak to give a clearer error message when validation fails due to extra fields in the pasted json schema to allow users to know what field was unexpected.
=> Update Json Validation error messages for additional fields

FormSchemas/jsonschema.json, __mocks__/retrieveIngestResponse.ts, __tests__/components/JSONEditor.test.tsx, __tests__/playwright/EditIngestPage.test.tsx
This closes #57 
Dashboard object in renders will now be required.  Mocks in tests were updated with that new requirement.
=> make renders dashboard object required and update tests

__tests__/components/JSONEditor.test.tsx, __tests__/playwright/CreateIngestPage.test.tsx, components/IngestForm.tsx, components/JSONEditor.tsx
when a user disables the strict schema checkbox on the json entry tab, they are able to add extra fields to submit in the Create Ingest flow.  There had been no way to clearly see the extra field names to verify that they were what was intended once the user returned to the Form tab.  This adds a card below the form listing the property names added.  I do not include the values for each property because that could get unnecessarily complex to handle displaying a more complex object.
=> Display additional properties on Form tab

__tests__/components/JSONEditor.test.tsx, __tests__/playwright/CreateIngestPage.test.tsx, components/AdditionalPropertyCard.tsx, components/IngestForm.tsx, components/JSONEditor.tsx
This moves the Additional Properties Card into a component that can be either an error or warning card and uses it on the json editor to make the appearance consistent:
=> Move additional properties card to component and use for errors

__mocks__/handlers.ts, __tests__/playwright/ThumbnailUploader.test.tsx, __tests__/playwright/ThumbnailUploaderDrawer.test.tsx, app/api/get-signed-url/route.ts, components/ThumbnailUploader.tsx, utils/s3.ts
This should be the final ticket to close out #4  and #59 
The uploaded thumbnails are not public, so the app needs to obtain a signed URL to display the preview.
This adds a new endpoint to retrieve the signed URL of the newly uploaded object.  The frontend then uses that signed url to display a preview image of the recently uploaded thumbnail
=> get upload image signed url to display it

__tests__/utils/FormValidation.test.ts, utils/CustomValidation.ts
this addresses #83  to ensure that the temporal extent End Date field is actually after the Start date.  The fields can still be empty, but if they are both used they must be in chronological order
=> validate start date is before end date

__tests__/components/JSONEditor.test.tsx, components/JSONEditor.tsx
i missed this in #84  but this PR this addresses the json editor to ensure that the temporal extent End Date field is actually after the Start date. The fields can still be empty, but if they are both used they must be in chronological order
=> validate start date is before end date on json editor

__tests__/components/JSONEditor.test.tsx, components/JSONEditor.tsx
this checks the json value entered into the JSON Editor component.  If a user has entered either `is_periodic` or `time_density` then a modal is opened.  The user can either leave the values unchanged and submit with he schema allowing extra fields or they can allow the application to automatically add the `dashboard:` prefix and continue submitting the JSON entry
=> give modal option to add dashboard: prefix if missing from is_periodic and time_density

FormSchemas/uischema.json, __tests__/playwright/CreateIngestPage.test.tsx, __tests__/playwright/utils/ValidateFormFields.tsx, utils/DiscoveryItemObjectFieldTemplate.tsx, utils/ObjectFieldTemplate.tsx
for some parts of the items in the Discovery Items, users rarely enter the optional fields and find them confusing.  It would be nice to hide them unless a user expands to see the additional rows
=> Add collapsible discovery section for some rows of Discovery Items

FormSchemas/datasets/uischema.json, __tests__/utils/AssetsField.test.tsx, __tests__/utils/BboxField.test.tsx, __tests__/utils/IntervalField.test.tsx, __tests__/utils/TestableUrlWidget.test.tsx, components/DatasetIngestionForm.tsx, utils/AssetsField.tsx, utils/IntervalField.tsx, utils/TestableUrlWidget.tsx, vitest.config.mts
closes #82 
This makes an API call to the staging validate url: https://staging.openveda.cloud/api/raster/cog/validate?strict=false&url=${encodedUrl}
It is considered valid if a `200` is recieved. 
This will give feedback for each sample feedback as validated, failed, or not yet validated:
=> add test button and validation api call for sample_files

FormSchemas/datasets/datasetSchema.json, __tests__/playwright/CreateDatasetPage.test.tsx, components/DatasetIngestionForm.tsx
In #101 I disabled the requirements for `cog_defaults` however if a user pastes in a config on the json editor without any values, the RJSF form automatically was re-inserting the default values. This sets those values by default on component load, but then allows the user to delete the values.
=> Manually set defaults to allow deletion via json editor

components/JSONEditor.tsx
this gives danger styling to leaving the pasted json without the `dashboard:` prefix and updates the text to say that it isn't the recommended option
=> encourage users to select dashboard prefix option

FormSchemas/collections/collectionSchema.json, FormSchemas/collections/uischema.json, FormSchemas/datasets/datasetSchema.json, FormSchemas/datasets/uischema.json, components/JSONEditor.tsx
This updates the Collection schema to allow the 3 different dashboard prefixes (dashboard:time_density,  dashboard:time_interval , and  dashboard:is_periodic)
It also adds the `dashboard:time_interval ` to the datasets schema.
Finally, it updates the modal for users that omit the `dashboard:` prefix to make it clearer the recommended change
=> handle dashboard:time_duration and improve json editor modal

__tests__/api/CreateIngestRoute.test.ts, __tests__/components/CreationFormManager.test.tsx, __tests__/playwright/CreateCollectionPage.test.tsx, __tests__/playwright/CreateDatasetPage.test.tsx, __tests__/playwright/ExtensionsAndAdditionalProperties.test.tsx, app/api/create-ingest/route.ts, components/CreationFormManager.tsx, components/SuccessModal.tsx, utils/githubUtils/CreatePR.ts
closes #112
This adds an additional modal to the creation form submission flow.  If a user enters text, it is placed in the PR body.  The comment is optional and is just a text area field for now, but Markdown formatting does get passed to the github client
=> Allow users to add optional additional notes for maintainers to the PR body

FormSchemas/collections/collectionSchema.json, FormSchemas/datasets/datasetSchema.json
this is a baby step to help support phase one as documented in [[DS 25.4 Multi-Tenancy] Add Multi-Tenant Support to VEDA Ingest UI](https://github.com/NASA-IMPACT/veda-ingest-ui/issues/123)https://github.com/NASA-IMPACT/veda-ingest-ui/issues/123 and https://github.com/NASA-IMPACT/veda-architecture/issues/630
This PR will add the "tenants" property to both collections and dataset json schemas. It doesn't add it to the UI schema. This will allow an array of strings for a key called `"tenant"` in the JSON Editor without the need for overriding the rest of the validation. I won't add the new `tenant` key to the UI Config yet. This will prevent anything new from being displayed on the form tab.
=> add tenant property to JSON Schema
